use_frameworks!

platform :ios, '8.0'

target 'FSModel_Example' do
  pod 'FSModel', :path => '../'

  target 'FSModel_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
  end
end
